name: my_recipes
description: My recipes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: 3.0.0
  cached_network_image: 3.0.0
  provider: 5.0.0
  url_launcher: 6.0.3
  cupertino_icons: 1.0.2
  cloud_firestore: 1.0.7
  firebase_storage: 8.0.5
  firebase_core: 1.1.0
  flutter_staggered_grid_view: 0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  #  flutter_launcher_icons: 0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_logo.png"

flutter:
  uses-material-design: true
